# Generated by Django 2.2.12 on 2021-03-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_name', models.CharField(max_length=50)),
                ('my_image', models.ImageField(default='Images/None/No-img.jpg', upload_to='Images/')),
            ],
        ),
    ]
