# Generated by Django 2.2.12 on 2021-05-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myimage',
            name='my_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
